parameters:
  AUTOMATIC_UPDATER_DISABLED: true
  DISABLE_WP_CRON: false
  # Disable the plugin and theme file editor in the admin
  DISALLOW_FILE_EDIT: true
  # Disable plugin and theme updates and installation from the admin
  DISALLOW_FILE_MODS: true
  # Limit the number of post revisions that WordPress stores (true (default WP): store every revision)
  WP_POST_REVISIONS: true
