version: '3.8'
services:
  database:
    image: 'mysql:8.0'
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/db/data:/var/lib/mysql:rw'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - '3306:3306'

  nginx:
    image: 'nginx:alpine'
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './docker/cert:/etc/nginx/certs'
    environment:
      # if you want to set custom host do not forget add to /etc/hosts
      - 'NGINX_HOST=localhost'
    ports:
      - '8000:8000'
      - '443:443'
    depends_on:
      - php

  php:
    build: docker/php-fpm
    working_dir: /app
    volumes:
      - '.:/app:rw'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    depends_on:
      - database
