parameters:
  SAVEQUERIES: true
  WP_DEBUG: "%env(bool:WP_DEBUG)%"
  WP_DEBUG_DISPLAY: true
  WP_DEBUG_LOG: "%env(WP_DEBUG_LOG)%"
  WP_DISABLE_FATAL_ERROR_HANDLER: false
  SCRIPT_DEBUG: true
  DISALLOW_INDEXING: true
  DISALLOW_FILE_MODS: false
